Module2 task1
htmlacademy-ecmascript/41846-cinemaddict-14 pull request #4
Opened 2021-04-09 09:23 UTC by Nikios05

2021-04-10 17:45 UTC, ant1quar requested changes
Ты неплохо справился. есть несколько комментов.
И нужно выпилить `dayjs` - в нем нет необходимости. лучше будет научиться работать с ванильным `Date`

2021-04-10 17:45 UTC, ant1quar commented on src/main.js
>  }
Не, давай чуть по другому.
1) в `allFilmsListContainer` ходить через индекс это не хорошо. заведи класс или id в самой верстке, который позволит тебе отделить `Top rated` от `Most commented` и по нему ориентируйся.
2) нужно вывести в константу количество фильмов, которые мы собираемся аппендить в каждый `allFilmsListContainer` и сденерить массив, длины этой константы. не нужны магические значения в коде.

2021-04-10 17:45 UTC, ant1quar commented on src/main.js
> +filmCountParagraph.innerHTML = `${COUNT_FILMS_VIEW} movies inside`;
Ну нет, сделай функцию, которая у тебя сгенерит футер. у этой функции будет параметр filmView, в который ты будешь передавать что-то

2021-04-10 17:45 UTC, ant1quar commented on src/mock/film.js
> +};
Огонь 👍

2021-04-10 17:45 UTC, ant1quar commented on src/mock/film.js
> +};
я вот не думаю, что тут есть необходимость в `dayjs`. п почему бы не `new Date().getFullYear() + yearGap`?

2021-04-10 17:45 UTC, ant1quar commented on src/mock/film.js
> +    originFilmName: possibleFilmNames[randomInt(0, 6)],
однотипная логика с магическими значениями. нужно унифицировать - напиши функцию `getRandomArrayElement`, куда передаешь массив, а получаешь случайный элемент массива.

2021-04-10 17:45 UTC, ant1quar commented on src/mock/film.js
> +    isFavorite: Boolean(randomInt(0, 1)),
Можно короче `!!randomInt(0,1)`

2021-04-10 17:45 UTC, ant1quar commented on src/utils.js
> +    return text.slice(0, 139) + '...';
магическое значение

2021-04-10 17:45 UTC, ant1quar commented on src/utils.js
> +export const shortenText = (text, characters = 140) => {
и тут

2021-04-10 17:45 UTC, ant1quar commented on src/mock/film.js
> +    isFavorite: Boolean(randomInt(0, 1)),
Зачем ты передаешь 0 и 1, если в `utils.js` они по умолчанию стоят?

2021-04-10 17:45 UTC, ant1quar commented on src/utils.js
> +};
А тут нужен `dayjs`?

2021-04-10 17:45 UTC, ant1quar commented on src/view/film-card.js
> +        <span class="film-card__genre">${film.filmGenres[0]}</span>
Почему тут магическое значение [0]?

2021-04-10 17:45 UTC, ant1quar commented on src/view/film-details.js
> +};
Давай через `map` и `join` перепишем, будет красивее

2021-04-10 17:45 UTC, ant1quar commented on src/view/film-details.js
> +const renderComment = (comment) => {
примени тут деструктуризацию сразу
Не так
`const renderComment = (comment) => {`
А так
`const renderComment = ({emotion, text, author, date}) => {`
И обращаться можно напрямую, без `comment.`

2021-04-10 17:45 UTC, ant1quar commented on src/mock/comments.js
> +    date: getFullDate(dayjs()),
`new Date()` тут не нужен `dayjs`

2021-04-11 15:08 UTC, Nikios05 commented on src/view/film-card.js
> +        <span class="film-card__genre">${film.filmGenres[0]}</span>
в карточке показывается 1 значение жанра

2021-04-11 17:06 UTC, Nikios05 commented on src/main.js
>  }
1. Добавил разные классы для блоков
2. Вынес значение в константу

2021-04-11 17:11 UTC, Nikios05 commented on src/main.js
> +filmCountParagraph.innerHTML = `${COUNT_FILMS_VIEW} movies inside`;
Вынес генерацию <p> в отдельную функцию в main, выносить в отдельный компонент не стал.

2021-04-11 17:11 UTC, Nikios05 commented on src/mock/film.js
> +};
Убрал dayjs из проекта, постарался все сделать через Date()

2021-04-11 17:12 UTC, Nikios05 commented on src/mock/film.js
> +    originFilmName: possibleFilmNames[randomInt(0, 6)],
Реализовал

2021-04-11 17:12 UTC, Nikios05 commented on src/mock/film.js
> +    isFavorite: Boolean(randomInt(0, 1)),
Поправил

2021-04-11 17:12 UTC, Nikios05 commented on src/utils.js
> +    return text.slice(0, 139) + '...';
Поправил

2021-04-11 17:12 UTC, Nikios05 commented on src/utils.js
> +export const shortenText = (text, characters = 140) => {
Поправил

2021-04-11 17:12 UTC, Nikios05 commented on src/utils.js
> +};
Убрал

2021-04-11 17:13 UTC, Nikios05 commented on src/view/film-details.js
> +};
Поправил

2021-04-11 17:13 UTC, Nikios05 commented on src/view/film-details.js
> +const renderComment = (comment) => {
Поправил

2021-04-11 17:13 UTC, Nikios05 commented on src/mock/comments.js
> +    date: getFullDate(dayjs()),
Убрал

2021-04-11 22:04 UTC, merged